import { Lesson } from "@/types";

export const LESSONS: Lesson[] = [
  {
    id: "action_verbs",
    title: "Action Verbs",
    subject: "english",
    subtitle: "Czasowniki czynnościowe",
  },
  {
    id: "jobs",
    title: "Jobs & Professions",
    subject: "english",
    subtitle: "Zawody i profesje",
  },
  {
    id: "kitchen_tools",
    title: "Kitchen Tools",
    subject: "english",
    subtitle: "Przybory kuchenne",
  },
  {
    id: "prepositions",
    title: "Prepositions of Place",
    subject: "english",
    subtitle: "Przyimki miejsca",
  },
  {
    id: "weather",
    title: "Weather",
    subject: "english",
    subtitle: "Pogoda",
  },
  {
    id: "articles",
    title: "A, An, The & At",
    subject: "english",
    subtitle: "Przedimki w praktyce",
    type: "articles",
  },
  {
    id: "clothing",
    title: "Clothing",
    subject: "english",
    subtitle: "Ubrania i odzież",
  },
  {
    id: "emotions",
    title: "Emotions",
    subject: "english",
    subtitle: "Uczucia i emocje",
  },
  {
    id: "fruits",
    title: "Fruits",
    subject: "english",
    subtitle: "Owoce i witaminy",
  },
  {
    id: "family",
    title: "Family Members",
    subject: "english",
    subtitle: "Członkowie rodziny",
  },
  {
    id: "food",
    title: "Food & Drinks",
    subject: "english",
    subtitle: "Jedzenie i napoje",
  },
  {
    id: "body_parts",
    title: "Body Parts",
    subject: "english",
    subtitle: "Części ciała",
  },
  {
    id: "furniture",
    title: "Furniture",
    subject: "english",
    subtitle: "Dom i meble",
  },
  {
    id: "vegetables",
    title: "Vegetables",
    subject: "english",
    subtitle: "Warzywa i ogród",
  },
  {
    id: "transport",
    title: "Transport",
    subject: "english",
    subtitle: "Pojazdy i podróże",
  },
  {
    id: "hobbies",
    title: "Hobbies",
    subject: "english",
    subtitle: "Czas wolny i pasje",
  },
  {
    id: "nature",
    title: "Nature",
    subject: "english",
    subtitle: "Natura i środowisko",
  },
  {
    id: "routines",
    title: "Daily Routines",
    subject: "english",
    subtitle: "Codzienne czynności",
  },
  {
    id: "tastes",
    title: "Tastes & Flavors",
    subject: "english",
    subtitle: "Smaki i doznania",
  },
  {
    id: "accessories",
    title: "Accessories",
    subject: "english",
    subtitle: "Dodatki i akcesoria",
  },
  {
    id: "chores",
    title: "House Chores",
    subject: "english",
    subtitle: "Obowiązki domowe",
  },
  {
    id: "hair",
    title: "Hair Styles",
    subject: "english",
    subtitle: "Włosy i fryzury",
  },
  {
    id: "final_test",
    title: "Final Test 🏆",
    subject: "english",
    subtitle: "Sprawdź swoje umiejętności",
  },
];
